/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminWhosamungusRouteImport } from './routes/admin.whosamungus'
import { Route as AdminUpsellsRouteImport } from './routes/admin.upsells'
import { Route as AdminTiktokRouteImport } from './routes/admin.tiktok'
import { Route as AdminRelacionadosRouteImport } from './routes/admin.relacionados'
import { Route as AdminProtecaoRouteImport } from './routes/admin.protecao'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPerfilRouteImport } from './routes/admin.perfil'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFreteRouteImport } from './routes/admin.frete'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminChaveRouteImport } from './routes/admin.chave'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhosamungusRoute = AdminWhosamungusRouteImport.update({
  id: '/admin/whosamungus',
  path: '/admin/whosamungus',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUpsellsRoute = AdminUpsellsRouteImport.update({
  id: '/admin/upsells',
  path: '/admin/upsells',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTiktokRoute = AdminTiktokRouteImport.update({
  id: '/admin/tiktok',
  path: '/admin/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRelacionadosRoute = AdminRelacionadosRouteImport.update({
  id: '/admin/relacionados',
  path: '/admin/relacionados',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtecaoRoute = AdminProtecaoRouteImport.update({
  id: '/admin/protecao',
  path: '/admin/protecao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/admin/produtos',
  path: '/admin/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: '/admin/perfil',
  path: '/admin/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFreteRoute = AdminFreteRouteImport.update({
  id: '/admin/frete',
  path: '/admin/frete',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/admin/clientes',
  path: '/admin/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChaveRoute = AdminChaveRouteImport.update({
  id: '/admin/chave',
  path: '/admin/chave',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/admin/categorias',
  path: '/admin/categorias',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/chave': typeof AdminChaveRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/frete': typeof AdminFreteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/protecao': typeof AdminProtecaoRoute
  '/admin/relacionados': typeof AdminRelacionadosRoute
  '/admin/tiktok': typeof AdminTiktokRoute
  '/admin/upsells': typeof AdminUpsellsRoute
  '/admin/whosamungus': typeof AdminWhosamungusRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/chave': typeof AdminChaveRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/frete': typeof AdminFreteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/protecao': typeof AdminProtecaoRoute
  '/admin/relacionados': typeof AdminRelacionadosRoute
  '/admin/tiktok': typeof AdminTiktokRoute
  '/admin/upsells': typeof AdminUpsellsRoute
  '/admin/whosamungus': typeof AdminWhosamungusRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/chave': typeof AdminChaveRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/frete': typeof AdminFreteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/protecao': typeof AdminProtecaoRoute
  '/admin/relacionados': typeof AdminRelacionadosRoute
  '/admin/tiktok': typeof AdminTiktokRoute
  '/admin/upsells': typeof AdminUpsellsRoute
  '/admin/whosamungus': typeof AdminWhosamungusRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/categorias'
    | '/admin/chave'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/frete'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/perfil'
    | '/admin/produtos'
    | '/admin/protecao'
    | '/admin/relacionados'
    | '/admin/tiktok'
    | '/admin/upsells'
    | '/admin/whosamungus'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/categorias'
    | '/admin/chave'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/frete'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/perfil'
    | '/admin/produtos'
    | '/admin/protecao'
    | '/admin/relacionados'
    | '/admin/tiktok'
    | '/admin/upsells'
    | '/admin/whosamungus'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin/categorias'
    | '/admin/chave'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/frete'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/perfil'
    | '/admin/produtos'
    | '/admin/protecao'
    | '/admin/relacionados'
    | '/admin/tiktok'
    | '/admin/upsells'
    | '/admin/whosamungus'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminChaveRoute: typeof AdminChaveRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFreteRoute: typeof AdminFreteRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminPerfilRoute: typeof AdminPerfilRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminProtecaoRoute: typeof AdminProtecaoRoute
  AdminRelacionadosRoute: typeof AdminRelacionadosRoute
  AdminTiktokRoute: typeof AdminTiktokRoute
  AdminUpsellsRoute: typeof AdminUpsellsRoute
  AdminWhosamungusRoute: typeof AdminWhosamungusRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whosamungus': {
      id: '/admin/whosamungus'
      path: '/admin/whosamungus'
      fullPath: '/admin/whosamungus'
      preLoaderRoute: typeof AdminWhosamungusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upsells': {
      id: '/admin/upsells'
      path: '/admin/upsells'
      fullPath: '/admin/upsells'
      preLoaderRoute: typeof AdminUpsellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tiktok': {
      id: '/admin/tiktok'
      path: '/admin/tiktok'
      fullPath: '/admin/tiktok'
      preLoaderRoute: typeof AdminTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/relacionados': {
      id: '/admin/relacionados'
      path: '/admin/relacionados'
      fullPath: '/admin/relacionados'
      preLoaderRoute: typeof AdminRelacionadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/protecao': {
      id: '/admin/protecao'
      path: '/admin/protecao'
      fullPath: '/admin/protecao'
      preLoaderRoute: typeof AdminProtecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/perfil': {
      id: '/admin/perfil'
      path: '/admin/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/frete': {
      id: '/admin/frete'
      path: '/admin/frete'
      fullPath: '/admin/frete'
      preLoaderRoute: typeof AdminFreteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chave': {
      id: '/admin/chave'
      path: '/admin/chave'
      fullPath: '/admin/chave'
      preLoaderRoute: typeof AdminChaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminChaveRoute: AdminChaveRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFreteRoute: AdminFreteRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminPerfilRoute: AdminPerfilRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminProtecaoRoute: AdminProtecaoRoute,
  AdminRelacionadosRoute: AdminRelacionadosRoute,
  AdminTiktokRoute: AdminTiktokRoute,
  AdminUpsellsRoute: AdminUpsellsRoute,
  AdminWhosamungusRoute: AdminWhosamungusRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
