/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSitesRouteImport } from './routes/admin.sites'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCardsRouteImport } from './routes/admin.cards'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSitesRoute = AdminSitesRouteImport.update({
  id: '/admin/sites',
  path: '/admin/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCardsRoute = AdminCardsRouteImport.update({
  id: '/admin/cards',
  path: '/admin/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/store': typeof StoreRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/store': typeof StoreRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/store': typeof StoreRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/store'
    | '/admin/analytics'
    | '/admin/cards'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/sites'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/store'
    | '/admin/analytics'
    | '/admin/cards'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/sites'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/store'
    | '/admin/analytics'
    | '/admin/cards'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/sites'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  StoreRoute: typeof StoreRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCardsRoute: typeof AdminCardsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminSitesRoute: typeof AdminSitesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sites': {
      id: '/admin/sites'
      path: '/admin/sites'
      fullPath: '/admin/sites'
      preLoaderRoute: typeof AdminSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cards': {
      id: '/admin/cards'
      path: '/admin/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof AdminCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  StoreRoute: StoreRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCardsRoute: AdminCardsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminSitesRoute: AdminSitesRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
